version: '3'

services:
  nginx:
    build: ./.build/docker/nginx
    restart: always
    ports:
      - "8889:80"
      - "4333:443"
    volumes:
      - ./:/app
      - ./.build/docker/nginx/nginx/:/etc/nginx/
    depends_on:
      - php

  php:
    build: ./.build/docker/php
    volumes:
      - ./:/app
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always

    volumes:
      - ./db_mysql:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: okn_2020
      MYSQL_DATABASE: okn_2020
      MYSQL_USER: okn_2020
      MYSQL_PASSWORD: okn_2020

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: myUserPass
  
  node:
    build:
      context: .
      dockerfile: ./.build/docker/node/Dockerfile
    image: okn_node
    depends_on:
      - nginx
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run prod
    ports:
      - "3000:3000"
      - "3001:3001"